<section id="headline" class="bone">
	<div class="container">
    	<h3><a href="#">Terms and Conditions</a></h3>
	</div>
</section>

<section class="container page-content">
	<hr class="vertical-space2">
    <section class="sixteen columns">
		
						<h4><strong>1. USE OF THIS SITE</strong></h4>
<p>1.1 Your access to and use of this site is subject to all applicable laws and regulations which apply to this site, to the Internet and/or to the World Wide Web, as well as these terms and conditions. Your accessing of this site and/or your use of this site constitutes acceptance of these terms and conditions without reservation, limitation or qualification.</p>
<p>1.2 These terms and conditions are subject to change at any time, and it is your responsibility to keep apprised of such changes. Any such change shall be effective immediately upon posting to this site. Your continued access and/or use of this site constitutes your continuing acceptance of these terms and conditions without reservation, limitation or qualification.</p>
<p>1.3 The information posted by the site operator on this site is believed to be accurate when posted, but is not warranted or represented in any way to be so. Any use or reliance on such information is at your own risk. Your access and/or use of this site is strictly on an “as is” basis, and you must not assume that this site will be error free or that it will operate without interruption or as intended.</p>
<h4><strong>2. THIS SITE DOES NOT PROVIDE MEDICAL ADVICE</strong></h4>
<p>2.1 The contents of this site are for informational purposes only. Text and information contained on this site, and reference to resource material is not intended to diagnose, treat, suggest a course of treatment, cure or prevent any disease, condition or malady. No warranty is made or given that any information on or linked to this site is complete and/or accurate, and no warranty is given that there may not be a contrary view to any of the material that is hereby published.</p>
<p>2.2 The information contained in this website, or obtained as a consequence of using this website is not intended to be, nor is it implied to be, a substitute for professional medical or pharmaceutical advice. Any user should always seek the advice of their physician, pharmacist, or other qualified health care provider prior to commencing any treatment for any conditions, diseases or maladies, and questions in relation to such treatment should be directed to such professional health care providers. Users should never disregard professional medical advice or delay in seeking such advice because of information obtained from this site. Reliance on any information provided on this site or provided by <strong>InnoviteHealth</strong> Inc. (“<strong>InnoviteHealth</strong>“) employees or others appearing on the site at the invitation of <strong>InnoviteHealth</strong> is solely at your own risk.</p>
<p>2.3 This site may contain content from third party sources. <strong>InnoviteHealth</strong> does not necessarily endorse any third party products, views or information presented on this site and such information or content may not reflect the opinions, recommendations or practices of <strong>InnoviteHealth</strong>.</p>
<p>2.4 Retailers of <strong>InnoviteHealth</strong> products using Genuine Expert or other information provided on this site to provide information or guidance to their customers must advise their customers that such information or advice is not intended to diagnose, treat, suggest a course of treatment, cure or prevent any disease, condition or malady and is not intended to be nor it is implied to be, a substitute for professional medical or pharmaceutical advice.  Retailers should counsel their customers to always seek the advice of their physician, pharmacist or other qualified healthcare provider prior to commencing any treatment for any conditions, diseases or maladies, and to direct questions in relation to such treatment to such professional healthcare providers.  Retailers should urge their customers never to disregard professional medical advice or delay in seeking such advice because of information provided by the retailer.</p>
<h4><strong>3. TRADEMARKS AND COPYRIGHT</strong></h4>
<p>3.1 This site contains the trademarks of <strong>InnoviteHealth</strong> including, but not limited to, the registered trademarks: adrena+, <strong>InnoviteHealth</strong>, just look for the leaves, leaves design, health &amp; happiness, enact+, grapes+, lean+, liv-tone, prost-flow, sleep+, “the green times”, transform+, vital vanilla, and “wellness watch”. All rights in respect of all of such trademarks are reserved.</p>
<p>3.2 Everything you see or read on this site is copyrighted unless otherwise noted, and nothing from this site may be used by you except as provided in these terms and conditions or in the text on the site without the prior written permission of <strong>InnoviteHealth</strong>. <strong>InnoviteHealth</strong> neither warrants nor represents that your use of materials displayed on or downloaded from this site will not infringe rights of third parties not owned by or affiliated with <strong>InnoviteHealth</strong>.</p>
<p>3.3 Nothing contained in this site should be construed as granting, by implication, estoppel or otherwise, any license or right to use any trademark, logo, service mark or design displayed on this site without the written permission of <strong>InnoviteHealth</strong> or any third party that may own any such item displayed on the site. Your use of any of the trademarks, logos, service marks, designs and other intellectual property displayed on this site and any other content on this site is strictly prohibited except only and to the limited extent expressly permitted in these terms and conditions. <strong>InnoviteHealth</strong> will aggressively enforce its intellectual property rights to the fullest extent of the law should you breach any of these terms and conditions.</p>
<h4><strong>4. SUBMISSIONS</strong></h4>
<p>4.1 Any communication or material you transmit to <strong>InnoviteHealth</strong> or through this site by electronic mail or otherwise, including any data, questions, comments, suggestions, testimonials or the like (all of which are collectively called “Submissions”), is and will be treated as non-confidential and non-proprietary. Any Submissions you transmit or post become the property of <strong>InnoviteHealth</strong> and its affiliates and may be used and exploited for any purpose including, but not limited to, reproduction, disclosure, transmission, publication, broadcast, posting and other exploitation in any way, whether for commercial gain or otherwise and with or without your name associated with the material, at <strong>InnoviteHealth</strong>’s election. <strong>InnoviteHealth</strong> is free to use any ideas, concepts, know-how, or techniques contained in any Submission for any purpose whatsoever including, but not limited to, developing, manufacturing and marketing products using such information. In that regard, by transmitting any Submission to <strong>InnoviteHealth</strong>, you will be deemed for all purposes to have assigned and transferred to <strong>InnoviteHealth</strong> all copyright, trademark and other intellectual property rights in and to the Submission and to have irrevocably waived and released all moral and/or personality rights in and to the Submission, and you acknowledge and agree that any act that is required to send a Submission will be deemed for all purposes to be your electronic signature to these terms and conditions.</p>
<p>4.2 Without limiting the generality of section 4.1 above, you agree to sign and deliver to <strong>InnoviteHealth</strong> on demand all further documents and assurances that <strong>InnoviteHealth</strong> may request in connection with the assignments, transfers, releases and waivers contemplated by that section.</p>
<p>4.3 <strong>InnoviteHealth</strong> is not responsible for any Submissions which may be posted in any forum or news group accessible or operated through or by this site, and <strong>InnoviteHealth</strong> will have the right (but not the obligation) to remove from any such forum or news group anything which it sees fit to remove for any reason. You must not submit or otherwise publish through this site or through any available forums or news groups anything which: (a) defames, libels or invades the privacy of any person; (b) is obscene, pornographic, abusive or threatening; (c) infringes on any intellectual property or other rights of any person or entity, including without limitation copyrights and trademarks; (d) violates any law; (e) advocates or describes any illegal activity; or (f) advertises or solicits funds for goods or services.</p>
<h4><strong>5. LIMITATION OF LIABILITY AND INDEMNITY</strong></h4>
<p>5.1 Your use of and browsing of this site are undertaken at your own risk. Neither <strong>InnoviteHealth</strong>, any of its directors, officers, employees, or agencies, nor any other party involved in the creation, production, delivery or operation of this site is liable for any direct, incidental, consequential, indirect, or punitive damages arising out of your access to or use of this site or any consequences flowing therefrom, including, without limitation, computer viruses which may infect or other damages which may occur to your computer equipment or other property as a result of your access, use of, or browsing of this site or your downloading of any materials, data, text, images, video or audio from this site.</p>
<p>5.2 Without limiting the generality of section 5.1, everything on this site is provided to you without any warranty or representation of any kind, whether expressed or implied, including but not limited to implied warranties of merchantability, fitness for a particular purpose, non-infringement or any other warranties which may be implied according to the laws of any jurisdiction, unless in your jurisdiction the exclusion of some or all of such expressed or implied warranties is not permitted or is restricted, in which case all such expressed or implied warranties are excluded to the fullest extent permitted by law in your jurisdiction.</p>
<p>5.3 You promise to indemnify and save <strong>InnoviteHealth</strong>, and its officers, directors, employees, agents and distributors, harmless from and against any and all claims, demands, liabilities, costs and expenses whatsoever, including without limitation reasonable legal fees and disbursements, resulting directly or indirectly from: (a) your breach of any of your agreements, representations or warranties set out in these terms and conditions; (b) your access to or use of this site or any site to which this site is or may be linked from time to time, or your use of, reliance on, or publication, communication or distribution of anything on or from this site or any site to which this site may be linked from time to time; and/or (c) your violation of any law or regulation.</p>
<p>5.4 Your sole remedy for dissatisfaction with this site, site-related services or products, content or information contained herein or on any hyperlinked website is to stop using the site, site-related services or products, content, information or hyperlinked website.</p>
<h4><strong>6. CONFIDENTIALITY AND PRIVACY ISSUES</strong></h4>
<p>6.1 Unless encrypted, information sent or received over the Internet is insecure and <strong>InnoviteHealth</strong> cannot and does not make any representation, warranty or promise concerning the interception by third parties of your personal or other information. <strong>InnoviteHealth</strong> will not be responsible for any damages you or any third party may suffer as a result of, or in connection with, the transmission of any information from or to <strong>InnoviteHealth</strong> through this site.</p>
<h4><strong>7. LINKED SITES</strong></h4>
<p>7.1 If and to the extent that any other sites on the World Wide Web are linked to this site at any time, <strong>InnoviteHealth</strong> is not responsible for the content of any such linked site or any link contained within such a linked site. <strong>InnoviteHealth</strong> reserves the right to terminate any link or linking program at any time and the linking of any site to or through this site does not imply any endorsement by <strong>InnoviteHealth</strong> of the companies, products or information offered described or otherwise made available on or through such linked sites. If you decide to access any site linked through or to this site, you do so entirely at your own risk.</p>
<h4><strong>8. PRIVACY STATEMENT</strong></h4>
<p>8.1 The Privacy Policy governing this site does not apply to information that we may collect from you by other means (including offline) or from other sources. It governs the collection, use and disclosure of the information we obtain from you when you subscribe for our Health &amp; Happiness online newsletter service, and any other information obtained from you through e-mail communications, whether general inquiries or otherwise, related to <strong>InnoviteHealth</strong>’s services. We use all information collected from you to complete information requests to the extent necessary to operate our programs, to provide the required services to you and to help in the development of <strong>InnoviteHealth</strong> services and products. All such communications we receive from you are also subject to the terms and conditions governing Submissions, stated elsewhere in these Terms and Conditions.</p>
<p>8.2 The information we collect is helpful to us in the development of <strong>InnoviteHealth</strong> services and products, but respect for our subscribers and viewers and their privacy rights motivates us to closely guard and protect that information. We do not share the individual information we gather on our site with third parties. Your individual privacy rights out-weigh any other considerations in this regard. There are no exceptions to this third party non-disclosure policy, except as may be permitted and required by law, and, without limitation, to fulfill regulatory requirements.</p>
<p>8.3 As with most Internet sites, the site collects a variety of technical data, including your IP address (a unique number that identifies your access account on the Internet), domain, and World Wide Web browser information. We do not log the specific identity of visitors. Technical data is used only to create broad demographic summaries of site usage and activity (such as average time spent and pages viewed) to assist us in providing useful content that is tailored to be of most value to our users. For example, we use the information to: give the developers of the site information that is useful in determining appropriate new features, content, and services; and to provide advertisers, partners and clients with aggregate – not individual – information about our user base. Information about individual users is not shared with any third party.</p>
<p>8.4 Our site may use “cookies”. This technology allows users to move more quickly through our site. Cookies are small text files that a Web site can use to recognize repeat users and facilitate the user’s ongoing access to and use of the site. For example, a cookie may store your password, or note your particular areas of interest. Generally, cookies work by assigning a unique number to the user that has no meaning outside the assigning site. We do not record or store any information about your movements on the Internet outside of the www.genuinehealth.com site. You can choose to decline our cookies (e.g., by setting your browser to reject cookies), but if you do, some parts of the site may not operate properly.</p>
<p>8.5 We keep personal information as accurate, complete, current and relevant as necessary for the identified purposes. An individual may challenge the accuracy and completeness of the personal information handled by us and have such information amended. An individual may also request access to their personal information. </p>
<h4><strong>9. JURISDICTION</strong></h4>
<p>9.1 These terms and conditions are governed by the laws of the Province of Ontario, without respect to its conflict of laws principles, and you expressly agree that exclusive jurisdiction for any dispute with <strong>InnoviteHealth</strong> in any way relating to this site resides in the courts of the Province of Ontario.</p>
											
  </section><!-- end-main-content --> 
	<br class="clear"><!-- end-sidebar-->
</section>